"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WomensSuffrage = exports.UnitedNations = exports.ShakespearesTheatre = exports.SetiProgram = exports.Pyramids = exports.Oracle = exports.MichelangelosChapel = exports.ManhattanProject = exports.MagellansExpedition = exports.Lighthouse = exports.JsBachsCathedral = exports.IsaacNewtonsCollege = exports.HooverDam = exports.HangingGardens = exports.GreatWall = exports.GreatLibrary = exports.DarwinsVoyage = exports.CureForCancer = exports.CopernicusObservatory = exports.Colossus = exports.ApolloProgram = void 0;
var ApolloProgram_1 = require("./Wonders/ApolloProgram");
Object.defineProperty(exports, "ApolloProgram", { enumerable: true, get: function () { return ApolloProgram_1.ApolloProgram; } });
var Colossus_1 = require("./Wonders/Colossus");
Object.defineProperty(exports, "Colossus", { enumerable: true, get: function () { return Colossus_1.Colossus; } });
var CopernicusObservatory_1 = require("./Wonders/CopernicusObservatory");
Object.defineProperty(exports, "CopernicusObservatory", { enumerable: true, get: function () { return CopernicusObservatory_1.CopernicusObservatory; } });
var CureForCancer_1 = require("./Wonders/CureForCancer");
Object.defineProperty(exports, "CureForCancer", { enumerable: true, get: function () { return CureForCancer_1.CureForCancer; } });
var DarwinsVoyage_1 = require("./Wonders/DarwinsVoyage");
Object.defineProperty(exports, "DarwinsVoyage", { enumerable: true, get: function () { return DarwinsVoyage_1.DarwinsVoyage; } });
var GreatLibrary_1 = require("./Wonders/GreatLibrary");
Object.defineProperty(exports, "GreatLibrary", { enumerable: true, get: function () { return GreatLibrary_1.GreatLibrary; } });
var GreatWall_1 = require("./Wonders/GreatWall");
Object.defineProperty(exports, "GreatWall", { enumerable: true, get: function () { return GreatWall_1.GreatWall; } });
var HangingGardens_1 = require("./Wonders/HangingGardens");
Object.defineProperty(exports, "HangingGardens", { enumerable: true, get: function () { return HangingGardens_1.HangingGardens; } });
var HooverDam_1 = require("./Wonders/HooverDam");
Object.defineProperty(exports, "HooverDam", { enumerable: true, get: function () { return HooverDam_1.HooverDam; } });
var IsaacNewtonsCollege_1 = require("./Wonders/IsaacNewtonsCollege");
Object.defineProperty(exports, "IsaacNewtonsCollege", { enumerable: true, get: function () { return IsaacNewtonsCollege_1.IsaacNewtonsCollege; } });
var JsBachsCathedral_1 = require("./Wonders/JsBachsCathedral");
Object.defineProperty(exports, "JsBachsCathedral", { enumerable: true, get: function () { return JsBachsCathedral_1.JsBachsCathedral; } });
var Lighthouse_1 = require("./Wonders/Lighthouse");
Object.defineProperty(exports, "Lighthouse", { enumerable: true, get: function () { return Lighthouse_1.Lighthouse; } });
var MagellansExpedition_1 = require("./Wonders/MagellansExpedition");
Object.defineProperty(exports, "MagellansExpedition", { enumerable: true, get: function () { return MagellansExpedition_1.MagellansExpedition; } });
var ManhattanProject_1 = require("./Wonders/ManhattanProject");
Object.defineProperty(exports, "ManhattanProject", { enumerable: true, get: function () { return ManhattanProject_1.ManhattanProject; } });
var MichelangelosChapel_1 = require("./Wonders/MichelangelosChapel");
Object.defineProperty(exports, "MichelangelosChapel", { enumerable: true, get: function () { return MichelangelosChapel_1.MichelangelosChapel; } });
var Oracle_1 = require("./Wonders/Oracle");
Object.defineProperty(exports, "Oracle", { enumerable: true, get: function () { return Oracle_1.Oracle; } });
var Pyramids_1 = require("./Wonders/Pyramids");
Object.defineProperty(exports, "Pyramids", { enumerable: true, get: function () { return Pyramids_1.Pyramids; } });
var SetiProgram_1 = require("./Wonders/SetiProgram");
Object.defineProperty(exports, "SetiProgram", { enumerable: true, get: function () { return SetiProgram_1.SetiProgram; } });
var ShakespearesTheatre_1 = require("./Wonders/ShakespearesTheatre");
Object.defineProperty(exports, "ShakespearesTheatre", { enumerable: true, get: function () { return ShakespearesTheatre_1.ShakespearesTheatre; } });
var UnitedNations_1 = require("./Wonders/UnitedNations");
Object.defineProperty(exports, "UnitedNations", { enumerable: true, get: function () { return UnitedNations_1.UnitedNations; } });
var WomensSuffrage_1 = require("./Wonders/WomensSuffrage");
Object.defineProperty(exports, "WomensSuffrage", { enumerable: true, get: function () { return WomensSuffrage_1.WomensSuffrage; } });
//# sourceMappingURL=Wonders.js.map